version: '3.2'

services:
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network
    ports:
      - 5555:5432

  backend: # rest api
    build: .
    container_name: 'backend'
    image: 'anticafe/backend:lastest'
    restart: always
    volumes:
      - ~/configs/appsettings.json:/app/appsettings.json
      - ~/logs:/app/log
    ports:
      - 445:443
      - 800:80  

networks:
  backend-network:
    driver: "bridge"

volumes:
  db_volume: