export const CREATE_BOOKING = 'CREATE_BOOKING';
export const FETCH_ALL_BOOKING = 'FETCH_ALL_BOOKING';
export const FETCH_BOOKING = "FETCH_BOOKING";
export const FETCH_USER_BOOKING = 'FETCH_USER_BOOKING';
export const DELETE_BOOKING = 'DELETE_BOOKING';
export const DELETE_ALL_BOOKING = 'DELETE_ALL_BOOKING';