export const EDIT_FEEDBACK = 'EDIT_FEEDBACK';
export const CREATE_FEEDBACK = 'CREATE_FEEDBACK';
export const FETCH_ALL_FEEDBACK = 'FETCH_ALL_FEEDBACK';
export const FETCH_FEEDBACK = 'FETCH_FEEDBACK';
export const DELETE_FEEDBACK = 'DELETE_FEEDBACK';
export const DELETE_ALL_FEEDBACK = 'DELETE_ALL_FEEDBACK';
