version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PortalDb
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ../postgres:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5555:5432"

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres    
    networks:
      - postgres  
  
  backend-1:
    build: .
    container_name: backend_api_1
    image: backend:latest
    restart: always
    volumes:
      - ./b-1/logs:/backend/logs/
    ports:
      - 443:443
      - 8080:80
    depends_on:
      - postgres   
    networks:
      - postgres   

  backend-2:
    build: .
    container_name: backend_api_2
    image: backend:latest
    restart: always
    volumes:
      - ./b-2/logs:/backend/logs/
    ports:
      - 8081:80
    depends_on:
      - postgres   
    networks:
      - postgres  

  backend-3:
    build: .
    container_name: backend_api_3
    image: backend:latest
    restart: always
    volumes:
      - ./b-3/logs:/backend/logs/
    ports:
      - 8079:80
    depends_on:
      - postgres   
    networks:
      - postgres  

  backend-mirror:
    build: .
    container_name: mirror-backend
    image: backend:latest
    restart: always
    volumes:
      - ./mb/logs:/backend/logs/
    ports:
      - 8078:80
    depends_on:
      - postgres   
    networks:
      - postgres  

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../docs:/usr/share/nginx/documentation
      - ../www-root/static:/usr/share/nginx/static
      - ../www-root/docs/readme.html:/usr/share/nginx/documentation/readme.html
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/logs:/var/log/nginx
    ports:
      - 80:80

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
