version: '3.9'

services:
  postgres:
    container_name: portal-postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PortalDb
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5555:5432"

  pgadmin4:
    container_name: portal-pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - "postgres"    
    networks:
      - postgres  
  
  backend: # rest api
    build: .
    container_name: portal-backend
    image: portal-backend:latest
    restart: always
    ports:
      - 443:443
      - 8080:80
    depends_on:
      - "postgres"   
    networks:
      - postgres   

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
