version: '3.9'

services:
  #######################################
  # БАЗЫ ДАННЫХ
  #######################################
  postgres-master-1:
    container_name: postgres_master_1
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PortalDb
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ../data/postgres-master-1/:/var/lib/postgresql/data
    networks:
      - postgres
    ports:
      - "5555:5432"

  postgres-master-2:
    container_name: postgres_master_2
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: PortalDb
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ../data/postgres-master-2/:/var/lib/postgresql/data
    depends_on:
      - postgres-master-1
    networks:
      - postgres
    ports:
      - "5556:5432"

  #######################################
  # АДМИНКА ДЛЯ БАЗ ДАННЫХ
  #######################################
  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres-master-1
      - postgres-master-2    
    networks:
      - postgres  
  
  #######################################
  # BACKEND
  #######################################
  backend-1:
    #build: .
    container_name: backend_api_1
    image: mansurow/portal-backend:latest
    restart: always
    volumes:
      - ./b-1/logs:/backend/logs/
    ports:
      - 8080:80
    depends_on:
      - postgres-master-1   
    networks:
      - postgres   

  backend-2:
    #build: .
    container_name: backend_api_2
    image: mansurow/portal-backend:latest
    restart: always
    volumes:
      - ./b-2/logs:/backend/logs/
    ports:
      - 8081:80
    depends_on:
      - postgres-master-1
      - backend-1   
    networks:
      - postgres  

  backend-3:
    #build: .
    container_name: backend_api_3
    image: mansurow/portal-backend:latest
    restart: always
    volumes:
      - ./b-3/logs:/backend/logs/
    ports:
      - 8079:80
    depends_on:
      - postgres-master-1
      - backend-1   
    networks:
      - postgres  

  backend-mirror:
    #build: .
    container_name: mirror-backend
    image: mansurow/portal-backend:mirror
    restart: always
    volumes:
      - ./b-m/logs:/backend/logs/
    ports:
      - 8078:80
    depends_on:
      - postgres-master-2   
    networks:
      - postgres  

  #######################################
  # NGINX
  #######################################
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../docs:/usr/share/nginx/documentation
      - ../www-root/static:/usr/share/nginx/static
      - ../www-root/render.html:/usr/share/nginx/documentation/render.html
      - ../www-root/render.html:/usr/share/nginx/apache/render.html
      - ../www-root/apache:/usr/share/nginx/apache/
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../nginx/ssl:/etc/nginx/ssl
      - ../nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443

networks:
  postgres:
    driver: bridge

volumes:
  postgres: 
  pgadmin:
